### ISSUE TITLE
NMDC DataHarmonizer feedback

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#90] opened 2022-01-24 22:22 UTC
Please see https://github.com/microbiomedata/DataHarmonizer/wiki and add your comment to this issue

**Comment by mslarae13** [comment] 2022-01-25 00:32
1. Help -> SOP vs Reference Guide
- We should work on this and make sure we're providing good documention.
- Looks like this is supposed to be the read me with all the definitions. But, they show the same thing but one for soil the other for water..
2. Ordering of the "sections" & columns - Mark is working on this
3. How many colors can we use/ highlight?
4. Why does it say emsl:defaut? Can we update this text?
5. No issues with the jump to or show/ hide. That was clear and worked well.

**Comment by turbomam** [comment] 2022-01-25 00:42
For https://github.com/microbiomedata/DataHarmonizer/issues/90#issuecomment-1020688221

3. only yellow and fuchsia for Column Headers and pink/red for invalid cells (unless we delve into DH JavaScript code)
4. yes that will be fixed as part of the section overhaul

**Comment by ssarrafan** [comment] 2022-01-25 17:45
Minor observations: When I click the validation button and it finds the errors and if I correct them they still show up as red until I validate again.  I assume this is as designed.  Also, once it doesn't find any more errors the no errors button fades away very quickly.  Would it make sense to keep the no errors button up longer (and maybe green)?  

Otherwise everything worked. I was able to add a row of data, validate it, save it as TSV and get information about the column headings by double clicking them. Also changing between required, required + etc all worked very smoothly.

**Comment by turbomam** [comment] 2022-01-25 18:39
analysis type mutiselect only includes metabolomics

**Comment by turbomam** [comment] 2022-01-25 18:40
example file download may get a bogus .html extension... provide documentation for removing

**Comment by ssarrafan** [comment] 2022-01-25 18:48
> analysis type mutiselect only includes metabolomics

actually only includes natural organic matter @turbomam

**Comment by turbomam** [comment] 2022-01-25 18:51
[DH usability insights - prioritization](https://docs.google.com/spreadsheets/d/1WKSYjh4kHSrYra3kvBNlGcYcTgPo6GhEPf8Epeh1Yw8/edit#gid=0)

**Comment by ssarrafan** [comment] 2022-01-28 19:30
@turbomam I'm going to continue this issue through February since the testing is in progress.

**Comment by ssarrafan** [comment] 2022-02-28 18:52
@turbomam can we close this issue?  I believe you've addressed all the feedback at this point.

**Comment by ssarrafan** [comment] 2022-03-01 18:09
Closing for now. Will anticipate new feedback from GSP workshop.

**Closed as completed by ssarrafan** 2022-03-01 18:09 UTC
